### PR TITLE
asap messaging, localization efforts, codestyle

### PR DESCRIPTION
**Pull request by applehat**
- Fitbit ASAP, replacing standard message class
- Added Localization Support (so far only on Alerts) with Languages:
  - English
   - Spanish
- Massive Codestyle pass (fitbit studio made some really hard to read indents when converting to VSCode)

https://github.com/Rytiggy/Glance/issues/56

### CODE REVIEW

**Comment by applehat** [comment]
I should have waited to do the codestyle cleanup outside of actual file changes.

I realize this is gonna be a pain to actually code review. 

(it builds and works tho -- if you'd rather just test it haha)

**Comment by applehat** [comment]
## Do not merge

There appears to be an issue with the ASAP logic.

**Comment by applehat** [comment]
This is tested and functional now.

**Comment by Rytiggy** [comment]
Looks good ready to merge 💯

**Pull request merged**
